user:
  outputs:
    default:
      account: PFBPDZG_WK44198
      auth_type: password
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      database: OPENCLASSROOMS_DB
      password: Openclassroom2026!
      retry_on_database_errors: true
      role: null
      schema: dbt_luciegefflot
      threads: 6
      type: snowflake
      user: lucie.gefflot@gmail.com
      warehouse: SNOWFLAKE_LEARNING_WH
  target: default
