version: 2

models:
  - name: mart_students_enriched
    description: "Table finale enrichie au niveau de l'apprenant."
    columns:
      - name: user_id
        description: "Identifiant unique de l'étudiant."
        tests:
          - unique
          - not_null

      - name: region
        description: "Région de l'étudiant."
        tests:
          - not_null

      - name: nb_etudiants_region
        description: "Nombre total d'étudiants dans la région."
        tests:
          - not_null

      - name: taux_penetration_pour_100k_hab
        description: "Taux de pénétration pour 100 000 habitants."
        tests:
          - not_null